// Photo credits for public/images. Required for CC BY images; listed for CC0 as a courtesy.
export const photoCredits = [
  { file: "hero-coach.jpg", title: "Dubai Marina and Sheikh Zayed Road from Saba 3 JLT at night", creator: "Yourusernamewillbepublic2", license: "CC0 1.0", licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en/", source: "https://commons.wikimedia.org/w/index.php?curid=167544579" },
  { file: "why-us.jpg", title: "Toyota Coaster GX XZB70 interior", creator: "Ypy31", license: "CC0 1.0", licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en/", source: "https://commons.wikimedia.org/w/index.php?curid=98612557" },
  { file: "about-karama.jpg", title: "An Edge of Karama", creator: "Dennis Sylvester Hurd", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0/", source: "https://commons.wikimedia.org/w/index.php?curid=123182416" },
  { file: "about-operations.jpg", title: "NIJ-359 Mercedes Tourismo in Békéscsaba", creator: "Tothh417", license: "CC0 1.0", licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en/", source: "https://commons.wikimedia.org/w/index.php?curid=73561221" },
  { file: "fleet-hiace-01.jpg", title: "Toyota HiAce Van DX '20 (2)", creator: "Oq10pass", license: "CC0 1.0", licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en/", source: "https://commons.wikimedia.org/w/index.php?curid=181950451" },
  { file: "fleet-hiace-02.jpg", title: "2020 Toyota HiAce (front)", creator: "User3204", license: "CC BY 4.0", licenseUrl: "https://creativecommons.org/licenses/by/4.0/", source: "https://commons.wikimedia.org/w/index.php?curid=100451138" },
  { file: "fleet-coaster-01.jpg", title: "Toyota Coaster GX XZB70", creator: "Ypy31", license: "CC0 1.0", licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en/", source: "https://commons.wikimedia.org/w/index.php?curid=63384538" },
  { file: "fleet-coaster-02.jpg", title: "Toyota Coaster GX XZB50", creator: "Ypy31", license: "CC0 1.0", licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en/", source: "https://commons.wikimedia.org/w/index.php?curid=108535040" },
  { file: "fleet-coach-01.jpg", title: "Moscow, Yutong coach on Valovaya Street, Mar 2026 01", creator: "Retired electrician", license: "CC0 1.0", licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en/", source: "https://commons.wikimedia.org/w/index.php?curid=186753509" },
  { file: "service-staff.jpg", title: "Dubai Marina and Sheikh Zayed Road from Saba 3 JLT", creator: "Yourusernamewillbepublic2", license: "CC0 1.0", licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en/", source: "https://commons.wikimedia.org/w/index.php?curid=167544583" },
  { file: "service-school.jpg", title: "Toyota Coaster EX XZB70", creator: "Ypy31", license: "CC0 1.0", licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en/", source: "https://commons.wikimedia.org/w/index.php?curid=63384796" },
  { file: "service-rental.jpg", title: "2021 Toyota HiAce", creator: "User3204", license: "CC BY 4.0", licenseUrl: "https://creativecommons.org/licenses/by/4.0/", source: "https://commons.wikimedia.org/w/index.php?curid=125864933" },
  { file: "service-airport.jpg", title: "Dubai airport glass roof", creator: "Unknown", license: "CC0 1.0", licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/", source: "https://www.rawpixel.com/image/6029447/photo-image-public-domain-blue-glass" },
  { file: "service-events.jpg", title: "Dubai skyline unsplash", creator: "Robert Bock", license: "CC0 1.0", licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/deed.en/", source: "https://commons.wikimedia.org/w/index.php?curid=82583102" },
  { file: "service-intercity.jpg", title: "On Rout to Abu Dhabi from Dubai (5).JPG", creator: "Producer", license: "CC BY 2.5", licenseUrl: "https://creativecommons.org/licenses/by/2.5/", source: "https://commons.wikimedia.org/w/index.php?curid=4914224" },
];
